### ISSUE TITLE
Unknown at rule @tailwind

### ISSUE THREAD

**Issue by mk66-coding** [adrianhajdin/nike_landing_page#2]
@tailwind base;
@tailwind components;
@tailwind utilities;
  .input {
    @apply sm:flex-1 max-sm:w-full text-base leading-normal text-slate-gray pl-5 max-sm:p-5 outline-none sm:border-none border max-sm:border-slate-gray max-sm:rounded-full;
  }
  hello. when i run npm run build
i get error message that these are unknown rule css

we use them in components but they are unknown.and dont let me to do npm run build or npm run deploy.
how can i fix them?
dist/assets/index-acd33682.css 
also error here -webkit-appearance:button
Also define the standard property 'appearance' for compatibilitycss(vendorPrefix)
🚨️ Property is nonstandard. Avoid using it.

Changes the appearance of buttons and other controls to resemble native controls.

(Chrome, Safari 3)
what are all these about?
@adrianhajdin

**Comment by YSoSeriousMax** [comment]
Hi I got this error as well to solve this, please download the extension on vscode called:
Tailwind css directives.
for more info please view here: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/69
note: after completing the steps the error will still show up however your css custom code can now be seen so you can just ignore that code.

**Comment by mk66-coding** [comment]
thanks the problem solved
